--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pleasepoggitwork/Super-Vouchers
build-by-default: true
branches:
- master
projects:
  Super-Vouchers:
    path: ""
    lint:
      phpstan: false
...
